### ISSUE TITLE
Purpose of the standard and the EF Marker?

### ISSUE THREAD

**Issue by Danconnolly** [bitcoin-sv/BRCs#39]
### BRC ID #

30

### Discussion

Why include the EF Marker?

The fact that a library that does not support EF can not read an EF transaction using this marker is not a valid reason. A well-written library would raise an error on attempted to decode an EF even if it did not have this marker.

In existing Bitcoin there are no type markers in the serialized form of bitcoin objects. Instead an INV Type is used when requesting data and a separate "command" is used when sending data between peers. It would be more in keeping with the existing design to extend the INV Type with a new type and use a separate P2P command for Extended Transactions.

**Comment by sirdeggen** [comment]
That's a great point. I think that the EF marker is to ensure that libraries which interpret transactions like bsv and go-bt don't parse the extended format data as outputs or something like that. There might be an unlucky case where some of the added data could be interpreted in a way which creates a valid transaction object which is not at all like the transaction intended. This assumes that the parser just keeps parsing without knowing about the overall length of the transaction in bytes, only referring to local var ints while it parses each chunk. The flag breaks regular tx parsers before there is a chance for that to happen.

That was the intention, but I think your point still stands.
