### ISSUE TITLE
[DISCUSSION] - "Standard"

### ISSUE THREAD

**Issue by sirdeggen** [bitcoin-sv/BRCs#44]
### BRC ID #

0

### Discussion

The use of the word "standard" was discussed with the team this week and I'd like to propose that we rephrase some of the overview / intro readme to ensure this is not confusing to others.

The intention was to propose ideas, which can later become standards. Defining them as standards within their own context is fine, as they aspire to be. However, they are not yet standard in any meaningful way (with some obvious exceptions).

The language may put some off from putting forward their own novel ideas. I think we'd be better encourage people to come forward and share their thoughts on how things ought to be done if we were to rephrase to something more like "technical proposals" or "initial thoughts" or "Bitcoin Requests for Comment" I suppose would be most appropriate.

**Comment by ty-everett** [comment]
Related PR: #45

**Comment by sirdeggen** [comment]
I don't expect to have time to complete this draft - @ty-everett please take this on with your team as part of the final section of work if appropriate.

**Comment by ty-everett** [comment]
After reviewing this proposal, I went ahead and merged the changes, and will make other changes as necessary to achieve the desired goals. With these changes, I will mark this discussion as resolved. If there are other suggestions, feel free to re-open the discussion.
